pipeline {
    agent { label 'vladimir' } // Exécute sur le slave "vladimir"
    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                bat 'pip install -r JenkinsVladimir/requirements.txt'
            }
        }

        stage('Clean Old Report') {
            steps {
                echo 'Deleting old report.xml if it exists...'
                bat 'if exist JenkinsVladimir\\report.xml del /F /Q JenkinsVladimir\\report.xml'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                bat 'pytest JenkinsVladimir/test_calculator.py --junitxml=report.xml'
            }
        }
        stage('Copy Report to Git Folder') {
            steps {
                echo 'Copying report.xml to JenkinsVladimir folder...'
                bat 'move report.xml JenkinsVladimir/'
            }
        }
        stage('Commit and Push Report to Git') {
            steps {
                echo 'Committing and pushing report.xml to GitHub...'
                withCredentials([string(credentialsId: 'github-credentials', variable: 'GIT_PASS')]) {
                    bat """
                        git config user.name "Jenkins Bot"
                        git config user.email "jenkins@yourdomain.com"
                        git stash
                        git checkout vladimir
                        git pull --rebase origin vladimir
                        git stash pop || echo "No changes to pop"
                        git add JenkinsVladimir/report.xml
                        git commit -m "Add test report"
                        git push origin vladimir
                    """
                }
            }
        }

        stage('Publish Results') {
            steps {
                echo 'Publishing test results...'
                junit 'JenkinsVladimir/report.xml'
            }
        }
    }
}
