pipeline {
    agent { label 'vladimir' }

    environment {
        GIT_CREDENTIALS_ID = 'github-credentials'
        GIT_BRANCH = 'vladimir'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                bat 'pip install black || exit /b 0'
            }
        }

        stage('Check Code Format') {
            steps {
                echo 'Checking Black format...'
                bat 'black --check JenkinsVladimir2/script_to_format.py || exit /b 0'
            }
        }

        stage('Apply Formatting') {
            steps {
                echo 'Applying Black formatting...'
                bat 'black JenkinsVladimir2/script_to_format.py'
            }
        }
    }

    post {
        always {
            echo "Pipeline execution complete."
        }
        failure {
            echo "Build failed! Check logs."
        }
    }
}
