name: CI Pipeline

# Déclenche le workflow à chaque push ou pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérification du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Spécifie la version de Python

    # Étape 3 : Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Lancer les tests
    - name: Run tests
      run: |
        pytest

